apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  selector:
    run: login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080