apiVersion: v1
kind: Service
metadata:
  name: login-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: login-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
